export interface Question {
  id: string;
  category: "basic" | "special-effects" | "theatrical";
  question: string;
  choices: string[];
  correctIndex: number;
  sectionCode: string;
  rationale: string;
}

export const osfmQuestions: Question[] = [
  {
    id: "q1",
    category: "basic",
    question: "UNDER CA TITLE 19, WHAT IS THE MINIMUM AGE REQUIREMENT FOR AN APPLICANT TO BE ELIGIBLE FOR A PYROTECHNIC OPERATOR LICENSE?",
    choices: ["18 YEARS OLD", "19 YEARS OLD", "21 YEARS OLD", "25 YEARS OLD"],
    correctIndex: 2,
    sectionCode: "TITLE 19 CCR § 981.3",
    rationale: "PER STATE FIRE MARSHAL REGULATIONS, ANY INDIVIDUAL APPLYING FOR A COMMERCIAL OR SPECIAL EFFECTS PYROTECHNIC OPERATOR LICENSE MUST BE AT LEAST 21 YEARS OF AGE AT THE TIME OF APPLICATION."
  },
  {
    id: "q2",
    category: "basic",
    question: "ACCORDING TO THE OSFM REGULATIONS, A REPORTABLE ACCIDENT INVOLVING FIREWORKS OR PYROTECHNIC MATERIALS MUST BE REPORTED TO THE STATE FIRE MARSHAL WITHIN WHAT TIMEFRAME?",
    choices: ["IMMEDIATELY WITHIN 24 HOURS", "WITHIN 48 HOURS", "WITHIN 3 BUSINESS DAYS", "WITHIN 7 DAYS"],
    correctIndex: 0,
    sectionCode: "TITLE 19 CCR § 985.1",
    rationale: "ANY ACCIDENT, FIRE, OR EXPLOSION INVOLVING PYROTECHNIC OPERATORS OR DISPLAYS RESULTING IN INJURY OR PROPERTY DAMAGE MUST BE REPORTED TO THE OSFM IMMEDIATELY, NOT TO EXCEED 24 HOURS FROM THE INCIDENT."
  },
  {
    id: "q3",
    category: "basic",
    question: "WHAT IS THE STANDARD SEPARATION DISTANCE REQUIREMENT FOR A CLASS 1 (1.3G) OUTDOOR DISPLAY MORTAR UP TO 3 INCHES IN DIAMETER FROM THE NEAREST AUDIENCE AREA?",
    choices: ["75 FEET", "140 FEET", "210 FEET", "300 FEET"],
    correctIndex: 2,
    sectionCode: "TITLE 19 CCR § 1004.1",
    rationale: "TITLE 19 SPECIFIES SAFE FALL-OUT AND DISTANCE METRICS. FOR 3-INCH COMMERCIAL DISPLAY MORTARS, THE MINIMUM DISTANCE CLEARANCE TO PREVENT AUDIENCE INJURY IS CALCULATED AT A MINIMUM RADIUS OF 210 FEET."
  },
  {
    id: "q4",
    category: "basic",
    question: "WHICH FIREWORKS CLASSIFICATION IDENTIFIES SUBSTANCES POSSESSING A MASS EXPLOSION HAZARD UNDER MODERN UN AND DOT REGULATIONS ADOPTED BY THE OSFM?",
    choices: ["DIVISION 1.1G", "DIVISION 1.3G", "DIVISION 1.4G", "DIVISION 1.4S"],
    correctIndex: 0,
    sectionCode: "TITLE 19 CCR § 980",
    rationale: "DIVISION 1.1G SPECIFICALLY CATEGORIZES SUBSTANCES AND ARTICLES THAT HAVE A MASS EXPLOSION HAZARD, WHEREAS 1.3G DENOTES COMMERCIAL DISPLAY FIREWORKS POSSESSING A FIRE HAZARD BUT NO MASS EXPLOSION RISK."
  },
  {
    id: "q5",
    category: "basic",
    question: "UNDER CA CODES, A LICENSED PYROTECHNIC OPERATOR-IN-CHARGE MUST MAINTAIN A COMPLETE WRITTEN LOG OF ALL PUBLIC DISPLAYS FOR A MINIMUM RETENTION PERIOD OF HOW LONG?",
    choices: ["1 YEAR", "3 YEARS", "5 YEARS", "PERMANENTLY"],
    correctIndex: 1,
    sectionCode: "TITLE 19 CCR § 986.4",
    rationale: "STATE REGULATORY POLICIES COMMAND THE OPERATOR-IN-CHARGE TO ARCHIVE SECURE FILED PERFORMANCE RECORDS, REPORT LOGS, AND REFERENCE DISCHARGES FOR NO LESS THAN 3 YEARS FOLLOWING AN EVENT."
  }
];

export function getQuestionsByCategory(
  category: Question["category"]
): Question[] {
  return osfmQuestions.filter((q) => q.category === category);
}

export function getQuestionById(id: string): Question | undefined {
  return osfmQuestions.find((q) => q.id === id);
}